[hooks]
enter = "mise i -q && uv sync"

[tools]
ruff = "latest"
python = "3.13"
uv = "latest"

[tasks]
lint = "ruff format . && ruff check . --fix"
test = "uv run pytest"
console = "uv run textual console -x EVENT -x DEBUG -x SYSTEM"
debug = "uv run textual run --dev web-server.py"
